theme: minima
title: CODING together
author: Kawther Zineb AB
email: kawther.ab@outlook.fr
description: > # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Do you want to start coding ? Or would you like to improve your skills? 
  What ... you are in the right place !! 
  come with me and let's learn step by step how to perfect yourself in this stuff



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  KAWTHER-AB

show_excerpts: true # set to false to remove excerpts on the homepage
